version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Use anonymous volume for node_modules to avoid overwriting
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true 