[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install --production=false", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"